version: "3.1"
services:
  cmcl-postgres:
    image: postgres:12
    container_name: cmcl-postgres
    environment:
      POSTGRES_DB: camara
      POSTGRES_PASSWORD: cvleao22
    ports:
      - "5433:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    networks: 
      - default_cmcl
networks:
    default_cmcl:
        driver: bridge
